version: "3.3"
services:
  manager:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
    env_file:
      - ../.env
    hostname: db-manager
    ports:
      - "5432:5432"
    volumes:
      - ${DBDATA_MANAGER}/:/var/lib/postgresql/data
    restart: always
    command: -p 5432
    expose:
      - "5432"
